// <auto-generated />
using System;
using MicroShop.NotificationService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroShop.NotificationService.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroShop.NotificationService.Persistence.Entities.ConsumedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("Consumer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("TraceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trace_id");

                    b.HasKey("MessageId");

                    b.HasIndex("Consumer", "ConsumedAtUtc")
                        .HasDatabaseName("ix_consumed_messages_consumer_consumed_at");

                    b.ToTable("consumed_messages", (string)null);
                });

            modelBuilder.Entity("MicroShop.NotificationService.Persistence.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("customer_email");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at_utc");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_message_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_notifications_order_id");

                    b.HasIndex("SourceMessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_notifications_source_message_id");

                    b.HasIndex("CustomerEmail", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notifications_customer_email_created_at");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_body_not_blank", "length(btrim(body)) > 0");

                            t.HasCheckConstraint("ck_notifications_currency_length", "length(currency) = 3");

                            t.HasCheckConstraint("ck_notifications_customer_email_not_blank", "length(btrim(customer_email)) > 0");

                            t.HasCheckConstraint("ck_notifications_subject_not_blank", "length(btrim(subject)) > 0");

                            t.HasCheckConstraint("ck_notifications_total_nonnegative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("MicroShop.NotificationService.Persistence.Entities.Notification", b =>
                {
                    b.HasOne("MicroShop.NotificationService.Persistence.Entities.ConsumedMessage", "ConsumedMessage")
                        .WithOne("Notification")
                        .HasForeignKey("MicroShop.NotificationService.Persistence.Entities.Notification", "SourceMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsumedMessage");
                });

            modelBuilder.Entity("MicroShop.NotificationService.Persistence.Entities.ConsumedMessage", b =>
                {
                    b.Navigation("Notification");
                });
#pragma warning restore 612, 618
        }
    }
}
