// <auto-generated />
using System;
using MicroShop.ProductService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroShop.ProductService.Persistence.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260817164536_AddInventoryReservationConstraints")]
    partial class AddInventoryReservationConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroShop.ProductService.Persistence.Entities.InventoryReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_reservations_order_id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_inventory_reservations_status_created_at");

                    b.ToTable("inventory_reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservations_currency_vnd", "currency = 'VND'");

                            t.HasCheckConstraint("ck_inventory_reservations_release_timestamp_consistent", "(status = 'released' AND released_at_utc IS NOT NULL) OR (status = 'reserved' AND released_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_inventory_reservations_status_valid", "status IN ('reserved', 'released')");

                            t.HasCheckConstraint("ck_inventory_reservations_total_nonnegative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("MicroShop.ProductService.Persistence.Entities.InventoryReservationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_inventory_reservation_items_product_id");

                    b.HasIndex("ReservationId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_reservation_items_reservation_product");

                    b.ToTable("inventory_reservation_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_reservation_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_inventory_reservation_items_status_valid", "status IN ('reserved', 'released')");

                            t.HasCheckConstraint("ck_inventory_reservation_items_subtotal_nonnegative", "subtotal >= 0");

                            t.HasCheckConstraint("ck_inventory_reservation_items_unit_price_nonnegative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("MicroShop.ProductService.Persistence.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer")
                        .HasColumnName("available_stock");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Name", "Id")
                        .HasDatabaseName("ix_products_active_name_id");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_available_stock_nonnegative", "available_stock >= 0");

                            t.HasCheckConstraint("ck_products_currency_vnd", "currency = 'VND'");

                            t.HasCheckConstraint("ck_products_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_products_unit_price_nonnegative", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("MicroShop.ProductService.Persistence.Entities.InventoryReservationItem", b =>
                {
                    b.HasOne("MicroShop.ProductService.Persistence.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MicroShop.ProductService.Persistence.Entities.InventoryReservation", "Reservation")
                        .WithMany("Items")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("MicroShop.ProductService.Persistence.Entities.InventoryReservation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
